version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress_content:/var/www/html
      - nginx:/etc/nginx/ssl:ro
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - wordpress_content:/var/www/html
    networks:
      - inception
    secrets:
      - password
      - root_password
      - user
      - root_user
      - db_name
    expose:
      - "9000"

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - password
      - root_password
      - user
      - root_user
      - db_name
    expose:
      - "3306"


networks:
  inception:
    driver : bridge

volumes:
  mariadb:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/${USER_NAME}/data/db
  wordpress:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/${USER_NAME}/data/web
  wordpress_content:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/${USER_NAME}/data/web/wp-content
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/${USER_NAME}/data/requirements/nginx


secrets:
  password:
    file: ../secrets/password
  root_password:
    file: ../secrets/root_password
  user:
    file: ../secrets/user
  root_user:
    file: ../secrets/root_user
  db_name:
    file: ../secrets/db_name
