version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress_content:/var/www/html
      - nginx:/etc/nginx/ssl:ro
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - wordpress_content:/var/www/html
    networks:
      - inception
    secrets:
      - password
      - root_password
      - user
      - root_user
      - db_name
    expose:
      - "9000"

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - password
      - root_password
      - user
      - root_user
      - db_name
    expose:
      - "3306"

  redis:
    build: requirements/bonus/redis/.
    container_name: redis
    restart: unless-stopped
    command: redis-server --protected-mode no
    expose:
      - "6379"
    networks:
      - inception

  ftp:
    build: requirements/bonus/ftp/.
    container_name: ftp
    restart: unless-stopped
    volumes:
      - wordpress:/home/kkuhn/www
    ports:
      - "21:21"
      - "30000-30010:30000-30010"
    networks:
      - inception
    privileged: true

  adminer:
    build: requirements/bonus/adminer/.
    restart: unless-stopped
    container_name: adminer
    ports:
       - "8080:8080"
    networks:
      - inception

  static_site:
    build: requirements/bonus/static_website/.
    restart: unless-stopped
    container_name: static_site
    expose:
      - "81"
    networks:
      - inception

  cadvisor:
    build:
      context: requirements/bonus/cadvisor/.
      args:
        - CADVISOR_VERSION=v0.52.1
    container_name: cadvisor
    expose:
        - "8080"
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - inception

networks:
  inception:
    driver : bridge

volumes:
  mariadb:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/${USER_NAME}/data/db
  wordpress:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/${USER_NAME}/data/web
  wordpress_content:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/${USER_NAME}/data/web/wp-content
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/${USER_NAME}/data/requirements/nginx


secrets:
  password:
    file: ../secrets/password
  root_password:
    file: ../secrets/root_password
  user:
    file: ../secrets/user
  root_user:
    file: ../secrets/root_user
  db_name:
    file: ../secrets/db_name

